<?php
/**
 * CointestatariTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Real Estate
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CointestatariTest Class Doc Comment
 *
 * @category    Class
 * @description Cointestatari
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CointestatariTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Cointestatari"
     */
    public function testCointestatari()
    {
    }

    /**
     * Test attribute "id_soggetto"
     */
    public function testPropertyIdSoggetto()
    {
    }

    /**
     * Test attribute "codice_fiscale"
     */
    public function testPropertyCodiceFiscale()
    {
    }

    /**
     * Test attribute "denominazione"
     */
    public function testPropertyDenominazione()
    {
    }

    /**
     * Test attribute "data_nascita"
     */
    public function testPropertyDataNascita()
    {
    }

    /**
     * Test attribute "luogo_nascita"
     */
    public function testPropertyLuogoNascita()
    {
    }

    /**
     * Test attribute "descrizione_titolo"
     */
    public function testPropertyDescrizioneTitolo()
    {
    }

    /**
     * Test attribute "titolarita_orig"
     */
    public function testPropertyTitolaritaOrig()
    {
    }

    /**
     * Test attribute "regime"
     */
    public function testPropertyRegime()
    {
    }

    /**
     * Test attribute "regime_orig"
     */
    public function testPropertyRegimeOrig()
    {
    }

    /**
     * Test attribute "quota_orig"
     */
    public function testPropertyQuotaOrig()
    {
    }

    /**
     * Test attribute "percentuale_quota"
     */
    public function testPropertyPercentualeQuota()
    {
    }

    /**
     * Test attribute "data_aggiornamento"
     */
    public function testPropertyDataAggiornamento()
    {
    }
}
