<?php
/**
 * DatiCatastaliTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Real Estate
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DatiCatastaliTest Class Doc Comment
 *
 * @category    Class
 * @description Dati catastali
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DatiCatastaliTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DatiCatastali"
     */
    public function testDatiCatastali()
    {
    }

    /**
     * Test attribute "codice_belfiore"
     */
    public function testPropertyCodiceBelfiore()
    {
    }

    /**
     * Test attribute "codice_comune"
     */
    public function testPropertyCodiceComune()
    {
    }

    /**
     * Test attribute "descrizione_comune"
     */
    public function testPropertyDescrizioneComune()
    {
    }

    /**
     * Test attribute "codice_provincia"
     */
    public function testPropertyCodiceProvincia()
    {
    }
}
