<?php
/**
 * FabbricatiPlusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Real Estate
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FabbricatiPlusTest Class Doc Comment
 *
 * @category    Class
 * @description FabbricatiPlus
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FabbricatiPlusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FabbricatiPlus"
     */
    public function testFabbricatiPlus()
    {
    }

    /**
     * Test attribute "id_immobile"
     */
    public function testPropertyIdImmobile()
    {
    }

    /**
     * Test attribute "codice_belfiore"
     */
    public function testPropertyCodiceBelfiore()
    {
    }

    /**
     * Test attribute "codice_comune"
     */
    public function testPropertyCodiceComune()
    {
    }

    /**
     * Test attribute "descrizione_comune"
     */
    public function testPropertyDescrizioneComune()
    {
    }

    /**
     * Test attribute "codice_provincia"
     */
    public function testPropertyCodiceProvincia()
    {
    }

    /**
     * Test attribute "foglio"
     */
    public function testPropertyFoglio()
    {
    }

    /**
     * Test attribute "particella"
     */
    public function testPropertyParticella()
    {
    }

    /**
     * Test attribute "denominatore_particella"
     */
    public function testPropertyDenominatoreParticella()
    {
    }

    /**
     * Test attribute "subalterno"
     */
    public function testPropertySubalterno()
    {
    }

    /**
     * Test attribute "sezione_amministrativa"
     */
    public function testPropertySezioneAmministrativa()
    {
    }

    /**
     * Test attribute "sezione_urbana"
     */
    public function testPropertySezioneUrbana()
    {
    }

    /**
     * Test attribute "classe"
     */
    public function testPropertyClasse()
    {
    }

    /**
     * Test attribute "indirizzo"
     */
    public function testPropertyIndirizzo()
    {
    }

    /**
     * Test attribute "piano"
     */
    public function testPropertyPiano()
    {
    }

    /**
     * Test attribute "codice_categoria"
     */
    public function testPropertyCodiceCategoria()
    {
    }

    /**
     * Test attribute "descrizione_categoria"
     */
    public function testPropertyDescrizioneCategoria()
    {
    }

    /**
     * Test attribute "valore_consistenza"
     */
    public function testPropertyValoreConsistenza()
    {
    }

    /**
     * Test attribute "unita_misura_consistenza"
     */
    public function testPropertyUnitaMisuraConsistenza()
    {
    }

    /**
     * Test attribute "rendita"
     */
    public function testPropertyRendita()
    {
    }

    /**
     * Test attribute "possessi"
     */
    public function testPropertyPossessi()
    {
    }

    /**
     * Test attribute "superficie_catastale"
     */
    public function testPropertySuperficieCatastale()
    {
    }

    /**
     * Test attribute "superficie_catastale_coperta"
     */
    public function testPropertySuperficieCatastaleCoperta()
    {
    }
}
