<?php
/**
 * RispostaStimaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Real Estate
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RispostaStimaTest Class Doc Comment
 *
 * @category    Class
 * @description RispostaStima
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RispostaStimaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RispostaStima"
     */
    public function testRispostaStima()
    {
    }

    /**
     * Test attribute "id_soggetto"
     */
    public function testPropertyIdSoggetto()
    {
    }

    /**
     * Test attribute "codice_fiscale"
     */
    public function testPropertyCodiceFiscale()
    {
    }

    /**
     * Test attribute "data_rapporto"
     */
    public function testPropertyDataRapporto()
    {
    }

    /**
     * Test attribute "numero_immobili"
     */
    public function testPropertyNumeroImmobili()
    {
    }

    /**
     * Test attribute "numero_fabbricati"
     */
    public function testPropertyNumeroFabbricati()
    {
    }

    /**
     * Test attribute "numero_terreni"
     */
    public function testPropertyNumeroTerreni()
    {
    }

    /**
     * Test attribute "fabbricati"
     */
    public function testPropertyFabbricati()
    {
    }

    /**
     * Test attribute "terreni"
     */
    public function testPropertyTerreni()
    {
    }
}
