<?php
/**
 * StimaFabbricatoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Real Estate
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StimaFabbricatoTest Class Doc Comment
 *
 * @category    Class
 * @description Stima Fabbricato
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StimaFabbricatoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StimaFabbricato"
     */
    public function testStimaFabbricato()
    {
    }

    /**
     * Test attribute "valore_min_normale"
     */
    public function testPropertyValoreMinNormale()
    {
    }

    /**
     * Test attribute "valore_max_normale"
     */
    public function testPropertyValoreMaxNormale()
    {
    }

    /**
     * Test attribute "valore_min_ottimo"
     */
    public function testPropertyValoreMinOttimo()
    {
    }

    /**
     * Test attribute "valore_max_ottimo"
     */
    public function testPropertyValoreMaxOttimo()
    {
    }

    /**
     * Test attribute "valore_min_scadente"
     */
    public function testPropertyValoreMinScadente()
    {
    }

    /**
     * Test attribute "valore_max_scadente"
     */
    public function testPropertyValoreMaxScadente()
    {
    }

    /**
     * Test attribute "valore_puntuale"
     */
    public function testPropertyValorePuntuale()
    {
    }

    /**
     * Test attribute "livello_confidenza"
     */
    public function testPropertyLivelloConfidenza()
    {
    }
}
