<?php
/**
 * TerreniBaseCointestatariTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Real Estate
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TerreniBaseCointestatariTest Class Doc Comment
 *
 * @category    Class
 * @description Lista dei terreni
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TerreniBaseCointestatariTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TerreniBaseCointestatari"
     */
    public function testTerreniBaseCointestatari()
    {
    }

    /**
     * Test attribute "id_immobile"
     */
    public function testPropertyIdImmobile()
    {
    }

    /**
     * Test attribute "classe"
     */
    public function testPropertyClasse()
    {
    }

    /**
     * Test attribute "foglio"
     */
    public function testPropertyFoglio()
    {
    }

    /**
     * Test attribute "particella"
     */
    public function testPropertyParticella()
    {
    }

    /**
     * Test attribute "denominatore_particella"
     */
    public function testPropertyDenominatoreParticella()
    {
    }

    /**
     * Test attribute "subalterno"
     */
    public function testPropertySubalterno()
    {
    }

    /**
     * Test attribute "sezione_censuaria"
     */
    public function testPropertySezioneCensuaria()
    {
    }

    /**
     * Test attribute "codice_porzione"
     */
    public function testPropertyCodicePorzione()
    {
    }

    /**
     * Test attribute "qualita"
     */
    public function testPropertyQualita()
    {
    }

    /**
     * Test attribute "superficie_ettari"
     */
    public function testPropertySuperficieEttari()
    {
    }

    /**
     * Test attribute "superficie_are"
     */
    public function testPropertySuperficieAre()
    {
    }

    /**
     * Test attribute "superficie_centiare"
     */
    public function testPropertySuperficieCentiare()
    {
    }

    /**
     * Test attribute "rendita_dominicale"
     */
    public function testPropertyRenditaDominicale()
    {
    }

    /**
     * Test attribute "rendita_agraria"
     */
    public function testPropertyRenditaAgraria()
    {
    }

    /**
     * Test attribute "possessi"
     */
    public function testPropertyPossessi()
    {
    }

    /**
     * Test attribute "catasto"
     */
    public function testPropertyCatasto()
    {
    }
}
